[supervisord]
nodaemon=true

[program:gunicorn]
command=gunicorn -w 4 -b unix:/run/app/gunicorn.sock app:app
autostart=true
autorestart=true

[program:nginx]
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
