apiVersion: v2
name: flask-app
version: 0.1.0
dependencies:
  - name: postgresql
    version: "15.5.0"
    repository: oci://registry-1.docker.io/bitnamicharts
  - name: redis
    version: "20.2.0"
    repository: oci://registry-1.docker.io/bitnamicharts
