# Flask приложение
replicaCount: 2
image:
  repository: kamushkinael/flask-app
  tag: latest
  pullPolicy: Always

resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

service:
  type: NodePort
  port: 80

# Имена внешних сервисов
externalServices:
  postgresHost: "flask-app-postgres"  # Будет заменено на имя релиза PostgreSQL
  redisHost: "flask-app-redis"         # Будет заменено на имя релиза Redis
