# Общие настройки
name: flask-app

# Flask приложение
replicaCount: 1
image:
  repository: kamushkinael/flask-app
  tag: latest
  pullPolicy: Always

# Ресурсы для Flask
resources:
  requests:
    memory: "128Mi"
    cpu: "100m"
  limits:
    memory: "256Mi"
    cpu: "200m"

# Сервис - МЕНЯЕМ НА NODEPORT!
service:
  type: NodePort  # Было ClusterIP
  port: 80

# PostgreSQL
postgres:
  image: postgres
  tag: 13-alpine
  user: user
  password: password
  database: mydb
  resources:
    requests:
      memory: "128Mi"
      cpu: "100m"
    limits:
      memory: "256Mi"
      cpu: "200m"
  healthcheck:
    enabled: true
    initialDelay: 30
    period: 10

# Redis
redis:
  image: redis
  tag: alpine
  password: ""
  resources:
    requests:
      memory: "64Mi"
      cpu: "50m"
    limits:
      memory: "128Mi"
      cpu: "100m"
  healthcheck:
    enabled: true
    initialDelay: 10
    period: 10
