apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.name }}
spec:
  rules:
  - host: flask-app.local  # или ваш реальный домен
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: {{ .Values.name }}
            port:
              number: {{ .Values.service.port }}
